version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: erp_sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong_Password123
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  sql_data: